/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BaseStorage__factory } from "./BaseStorage__factory";
export { Owned__factory } from "./Owned__factory";
